# PHP
# Test and package your PHP project.
# Add steps that run tests, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/php
resources:
  repositories:
  - repository: gitrepotogithub
    type: github
    name: prasadpandari/gitrepotogithub
    endpoint: prasadpandari
    ref: main
  - repository: php
    type: git
    name: PHP
    ref: develop 


trigger:
- develop

pool:
  vmImage: ubuntu-latest

variables:
  phpVersion: 7.2

steps:
- checkout: gitrepotogithub
- checkout: php
- script: |
    sudo update-alternatives --set php /usr/bin/php$(phpVersion)
    sudo update-alternatives --set phar /usr/bin/phar$(phpVersion)
    sudo update-alternatives --set phpdbg /usr/bin/phpdbg$(phpVersion)
    sudo update-alternatives --set php-cgi /usr/bin/php-cgi$(phpVersion)
    sudo update-alternatives --set phar.phar /usr/bin/phar.phar$(phpVersion)
    php -version
  displayName: 'Use PHP version $(phpVersion)'

- script: ls $(System.DefaultWorkingDirectory) 
  displayName: 'list working directory'

- script: ls $(Build.SourcesDirectory)
  displayName: 'list build staging'

- script: |
    cd PHP
    composer validate
  displayName: 'composer validate'

- script: ls  
  displayName: 'list current directory'

- script: ls $(Build.SourcesDirectory)
  displayName: 'list build staging'

- task: CopyFiles@2
  inputs:
    Contents: |
      **/*
      !.git/**/*
      !*.yml
    SourceFolder: PHP
    TargetFolder: gitrepotogithub
  
- script: |
    cd gitrepotogithub
    git status
    git remote -v
    git checkout main
    git config --global user.email "widgetdev@ups.com"
    git config --global user.name "widget dev"
    git add --all
    git commit -m "message"
    git push
  displayName: 'list staging directory' 